"""Add visible_to_sender/receiver

Revision ID: 20539c37fa5d
Revises: 433a76402756
Create Date: 2025-03-30 12:50:35.980236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20539c37fa5d'
down_revision = '433a76402756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visible_to_receiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('visible_to_receiver')
        batch_op.drop_column('visible_to_sender')

    # ### end Alembic commands ###
