"""Add DH key exchange fields to User model

Revision ID: 24b7ca543087
Revises: 
Create Date: 2025-04-25 16:01:28.203543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b7ca543087'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_dh_public', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('server_dh_private', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('server_dh_private')
        batch_op.drop_column('client_dh_public')

    # ### end Alembic commands ###
