"""Add retry_count to messages table

Revision ID: 3cd9a48e4fd0
Revises: 887008df4484
Create Date: 2025-04-19 10:49:16.861524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd9a48e4fd0'
down_revision = '887008df4484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visible_to_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visible_to_receiver', sa.Boolean(), nullable=True))
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('msg_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('seq_no',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=16),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('seq_no',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('msg_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('visible_to_receiver')
        batch_op.drop_column('visible_to_sender')
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###
