"""Add is_online and last_seen to User

Revision ID: 433a76402756
Revises: 6a00ee5c7c0b
Create Date: 2025-03-29 14:36:33.326496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433a76402756'
down_revision = '6a00ee5c7c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
