"""Add MTProto auth_key fields

Revision ID: 485fc698d3d1
Revises: 24b7ca543087
Create Date: 2025-04-25 22:39:36.799051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485fc698d3d1'
down_revision = '24b7ca543087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('client_dh_public')
        batch_op.drop_column('server_dh_private')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_dh_private', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('client_dh_public', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
