"""Add is_online and last_seen to User

Revision ID: 56a4151fa3e5
Revises: 20539c37fa5d
Create Date: 2025-04-16 23:40:04.995079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a4151fa3e5'
down_revision = '20539c37fa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('visible_to_receiver')
        batch_op.drop_column('visible_to_sender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_sender', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('visible_to_receiver', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
