"""Add visibility flags to messages

Revision ID: 78b1d938f743
Revises: 56a4151fa3e5
Create Date: 2025-04-16 23:51:20.942855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b1d938f743'
down_revision = '56a4151fa3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_sender', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visible_to_receiver', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('visible_to_receiver')
        batch_op.drop_column('visible_to_sender')

    # ### end Alembic commands ###
