"""Allow nullable msg_key and auth_key_id

Revision ID: 951161550bae
Revises: 485fc698d3d1
Create Date: 2025-04-26 19:52:30.437598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951161550bae'
down_revision = '485fc698d3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('msg_key',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('auth_key_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('auth_key_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('msg_key',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
