"""Updated schema for MTProto 2.0

Revision ID: ced914c47aa5
Revises: 3cd9a48e4fd0
Create Date: 2025-04-19 11:01:03.032829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced914c47aa5'
down_revision = '3cd9a48e4fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_id')
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
